a=int(input("Digite el valor para a: "))
b=int(input("Digite el valor para b: "))
division=a/b
print("el resultado de la división es:",division)

a=int(input("digite el valor para a: "))
b=int(input("digite el valor para b: "))
resta=a-b
print("el resultado de la resta es:",resta)

a=int(input("digite el valor de a: "))
b=int(input("digite el valor de b: "))
modulo=a%b
print("el residuo es:",modulo)

a=int(input("digite el valor de a:"))
b=int(input("digite el valor de b: "))
multiplicacion=a*b
print("el resultado de la multiplicación es:",multiplicacion)

a=int(input("digite el delor de a: "))
b=int(input("digite el valor de b: "))
suma=a+b
print("el resultado de la suma es:",suma)